[package]
name = "cdc_rust_scylla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
hex = "0.4"
scylla = "0.2"
tokio = { version = "1.12", features = ["full"] }
